ALTER TABLE `pembelian` 
  ADD COLUMN `subtotal` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
  ADD COLUMN `nilai_ppn` DECIMAL(5, 2) NOT NULL DEFAULT 0.00,
  ADD COLUMN `jenis_ppn` VARCHAR(50) DEFAULT 'tambah_ppn',
  ADD COLUMN `cashback` DECIMAL(15, 2) NOT NULL DEFAULT 0.00;

ALTER TABLE `pembeliandetail` 
  ADD COLUMN `diskon` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
  ADD COLUMN `diskon_tipe` VARCHAR(10) DEFAULT '%',
  ADD COLUMN `subtotal` DECIMAL(15, 2) NOT NULL DEFAULT 0.00;